name: quick_mart
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  go_router: ^14.6.2
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
